# Generated by Django 5.1.3 on 2025-10-16 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reyler', models.PositiveIntegerField(default=0, help_text='Rəylərin sayı və ya bəyənmə göstəricisi')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sual_sayisi', models.PositiveIntegerField(default=0)),
                ('sef_sayisi', models.PositiveIntegerField(default=0)),
                ('duz_sayisi', models.PositiveIntegerField(default=0)),
                ('duz_aparir', models.DecimalField(decimal_places=2, default=0.25, max_digits=5)),
                ('imtahan_tarixi', models.DateField()),
                ('imtahan_vaxti', models.TimeField()),
                ('odenissizdir', models.BooleanField(default=True)),
                ('hesab_tipi', models.PositiveSmallIntegerField(choices=[(1, 'Səhvlər düzgünlərə təsir etmir'), (2, 'Hər səhv öz balının ¼-ni aparır'), (3, 'Hər 4 səhv 1 düzü aparır')], default=1)),
                ('sual_bali', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('bali', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('duzgun_cavab', models.CharField(max_length=255)),
                ('sebeb', models.TextField(blank=True, help_text='Doğru cavabın izahı', null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='exam.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='exam.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubsubcategories', to='exam.subsubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subsubsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.subsubsubcategory'),
        ),
    ]
