# Generated by Django 5.1.3 on 2025-10-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='price',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='reyler',
        ),
        migrations.RemoveField(
            model_name='question',
            name='duzgun_cavab',
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, help_text='Cavab şəkli (əgər mətn deyilsə)', null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Bu cavab düzgündürmü?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(blank=True, help_text='Cavab mətni (əgər şəkil deyilsə)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='bali',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Bu sualın bal dəyəri', max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Sual şəkli (əgər mətn deyilsə)', null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sebeb',
            field=models.TextField(blank=True, help_text='Düzgün cavabın izahı', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, help_text='Sual mətni (əgər şəkil deyilsə)', null=True),
        ),
    ]
