# Generated by Django 5.1.3 on 2025-10-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_exam_price_remove_exam_reyler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'İmtahan', 'verbose_name_plural': 'İmtahanlar'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Alt Kateqoriya', 'verbose_name_plural': 'Alt Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='subsubcategory',
            options={'verbose_name': 'Alt Alt Kateqoriya', 'verbose_name_plural': 'Alt Alt Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='subsubsubcategory',
            options={'verbose_name': 'Alt Alt Alt Kateqoriya', 'verbose_name_plural': 'Alt Alt Alt Kateqoriyalar'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duz_aparir',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duz_sayisi',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='hesab_tipi',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='imtahan_tarixi',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='imtahan_vaxti',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='odenissizdir',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='sef_sayisi',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='sual_bali',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='sual_sayisi',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subsubsubcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subsubsubcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subsubsubcategory',
            name='subsubcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_az',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='exam',
            name='calculation_types',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Səhvlər düzgünlərə təsir etmir'), (2, 'Hər səhv öz balının ¼-ni aparır'), (3, 'Hər 4 səhv 1 düzü aparır')], default=1, verbose_name='Hesablama tipləri'),
        ),
        migrations.AddField(
            model_name='exam',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='exam',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='exam',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='exam',
            name='leads_straight',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=5, verbose_name='Düz aparır'),
        ),
        migrations.AddField(
            model_name='exam',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Qiymət'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_honey',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Sual Balı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='right_number',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Düz sayısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='row_number',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Səf sayısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sub_sub_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.subsubsubcategory', verbose_name='Alt Alt Alt Kateqoriya'),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_az',
            field=models.CharField(max_length=256, null=True, verbose_name='İmtahanın adı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='İmtahanın adı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='İmtahanın adı'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_az',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.subcategory', verbose_name='Alt Kateqoriya'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='title_az',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subsubsubcategory',
            name='sub_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.subsubcategory', verbose_name='Alt Alt Kateqoriya'),
        ),
        migrations.AddField(
            model_name='subsubsubcategory',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subsubsubcategory',
            name='title_az',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subsubsubcategory',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='subsubsubcategory',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(null=True, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=256, verbose_name='İmtahanın adı'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.category', verbose_name='Kateqoriya'),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_quest', models.ImageField(blank=True, null=True, upload_to='quest/', verbose_name='Sual şəkli')),
                ('title_quest', models.CharField(max_length=500, null=True, verbose_name='Sual Başlıq')),
                ('title_quest_az', models.CharField(max_length=500, null=True, verbose_name='Sual Başlıq')),
                ('title_quest_ru', models.CharField(max_length=500, null=True, verbose_name='Sual Başlıq')),
                ('title_quest_en', models.CharField(max_length=500, null=True, verbose_name='Sual Başlıq')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Sualın Balı')),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='answer/', verbose_name='Cavab A Şəkil')),
                ('title_a', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab A Başlıq')),
                ('title_a_az', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab A Başlıq')),
                ('title_a_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab A Başlıq')),
                ('title_a_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab A Başlıq')),
                ('is_correct_a', models.BooleanField(default=False, verbose_name='Cavab A Düzdür?')),
                ('explanation_a', models.TextField(blank=True, null=True, verbose_name='Cavab A İzahı')),
                ('explanation_a_az', models.TextField(blank=True, null=True, verbose_name='Cavab A İzahı')),
                ('explanation_a_ru', models.TextField(blank=True, null=True, verbose_name='Cavab A İzahı')),
                ('explanation_a_en', models.TextField(blank=True, null=True, verbose_name='Cavab A İzahı')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='answer/', verbose_name='Cavab B Şəkil')),
                ('title_b', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab B Başlıq')),
                ('title_b_az', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab B Başlıq')),
                ('title_b_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab B Başlıq')),
                ('title_b_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab B Başlıq')),
                ('is_correct_b', models.BooleanField(default=False, verbose_name='Cavab B Düzdür?')),
                ('explanation_b', models.TextField(blank=True, null=True, verbose_name='Cavab B İzahı')),
                ('explanation_b_az', models.TextField(blank=True, null=True, verbose_name='Cavab B İzahı')),
                ('explanation_b_ru', models.TextField(blank=True, null=True, verbose_name='Cavab B İzahı')),
                ('explanation_b_en', models.TextField(blank=True, null=True, verbose_name='Cavab B İzahı')),
                ('image_c', models.ImageField(blank=True, null=True, upload_to='answer/', verbose_name='Cavab C Şəkil')),
                ('title_c', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab C Başlıq')),
                ('title_c_az', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab C Başlıq')),
                ('title_c_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab C Başlıq')),
                ('title_c_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab C Başlıq')),
                ('is_correct_c', models.BooleanField(default=False, verbose_name='Cavab C Düzdür?')),
                ('explanation_c', models.TextField(blank=True, null=True, verbose_name='Cavab C İzahı')),
                ('explanation_c_az', models.TextField(blank=True, null=True, verbose_name='Cavab C İzahı')),
                ('explanation_c_ru', models.TextField(blank=True, null=True, verbose_name='Cavab C İzahı')),
                ('explanation_c_en', models.TextField(blank=True, null=True, verbose_name='Cavab C İzahı')),
                ('image_d', models.ImageField(blank=True, null=True, upload_to='answer/', verbose_name='Cavab D Şəkil')),
                ('title_d', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab D Başlıq')),
                ('title_d_az', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab D Başlıq')),
                ('title_d_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab D Başlıq')),
                ('title_d_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab D Başlıq')),
                ('is_correct_d', models.BooleanField(default=False, verbose_name='Cavab D Düzdür?')),
                ('explanation_d', models.TextField(blank=True, null=True, verbose_name='Cavab D İzahı')),
                ('explanation_d_az', models.TextField(blank=True, null=True, verbose_name='Cavab D İzahı')),
                ('explanation_d_ru', models.TextField(blank=True, null=True, verbose_name='Cavab D İzahı')),
                ('explanation_d_en', models.TextField(blank=True, null=True, verbose_name='Cavab D İzahı')),
                ('image_e', models.ImageField(blank=True, null=True, upload_to='answer/', verbose_name='Cavab E Şəkil')),
                ('title_e', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab E Başlıq')),
                ('title_e_az', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab E Başlıq')),
                ('title_e_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab E Başlıq')),
                ('title_e_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab E Başlıq')),
                ('is_correct_e', models.BooleanField(default=False, verbose_name='Cavab E Düzdür?')),
                ('explanation_e', models.TextField(blank=True, null=True, verbose_name='Cavab E İzahı')),
                ('explanation_e_az', models.TextField(blank=True, null=True, verbose_name='Cavab E İzahı')),
                ('explanation_e_ru', models.TextField(blank=True, null=True, verbose_name='Cavab E İzahı')),
                ('explanation_e_en', models.TextField(blank=True, null=True, verbose_name='Cavab E İzahı')),
                ('image_f', models.ImageField(blank=True, null=True, upload_to='answer/', verbose_name='Cavab F Şəkil')),
                ('title_f', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab F Başlıq')),
                ('title_f_az', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab F Başlıq')),
                ('title_f_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab F Başlıq')),
                ('title_f_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cavab F Başlıq')),
                ('is_correct_f', models.BooleanField(default=False, verbose_name='Cavab F Düzdür?')),
                ('explanation_f', models.TextField(blank=True, null=True, verbose_name='Cavab F İzahı')),
                ('explanation_f_az', models.TextField(blank=True, null=True, verbose_name='Cavab F İzahı')),
                ('explanation_f_ru', models.TextField(blank=True, null=True, verbose_name='Cavab F İzahı')),
                ('explanation_f_en', models.TextField(blank=True, null=True, verbose_name='Cavab F İzahı')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='exam.exam', verbose_name='İmtahan')),
            ],
            options={
                'verbose_name': 'Sual və Cavablar',
                'verbose_name_plural': 'Sual və Cavablar',
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
