# Generated by Django 5.1.3 on 2025-10-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_question_exam_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_a',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_a_az',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_a_en',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_a_ru',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_b',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_b_az',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_b_en',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_b_ru',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_c',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_c_az',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_c_en',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_c_ru',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_d',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_d_az',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_d_en',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_d_ru',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_e',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_e_az',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_e_en',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_e_ru',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_f',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_f_az',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_f_en',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='explanation_f_ru',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Düz Cavab İzahı'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='explanation_az',
            field=models.TextField(blank=True, null=True, verbose_name='Düz Cavab İzahı'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='explanation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Düz Cavab İzahı'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='explanation_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Düz Cavab İzahı'),
        ),
    ]
