# Generated by Django 5.1.3 on 2025-10-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_purchasedexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitmə tarixi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Alındığı tarix'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlama tarixi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
