# Generated by Django 5.1.3 on 2025-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_created_at_exam_end_date_exam_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedexam',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasedexam',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
