# Generated by Django 5.1.3 on 2025-10-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_purchasedexam_finished_at_purchasedexam_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='İstifadəçi imtahana başladıqda bu müddət hesablanacaq', null=True, verbose_name='İmtahan müddəti (dəqiqə)'),
        ),
    ]
