# Generated by Django 5.1.3 on 2025-11-12 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_exam_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Ulduz sayı (1-5)')),
                ('comment', models.TextField(verbose_name='Rəy mətni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma tarixi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exam.exam', verbose_name='İmtahan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'İmtahan rəyi',
                'verbose_name_plural': 'İmtahan rəyləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
