# Generated by Django 5.1.3 on 2025-11-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_examreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Əsas imtahandır? Ana səhifədə'),
        ),
    ]
