# Generated by Django 5.1.3 on 2025-11-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_exam_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Şəkil'),
        ),
    ]
