# Generated by Django 5.1.3 on 2025-11-12 12:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_exam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='active_period',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aktiv olma müddəti yazısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='active_period_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aktiv olma müddəti yazısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='active_period_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Aktiv olma müddəti (günlərlə)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='active_period_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aktiv olma müddəti yazısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='active_period_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aktiv olma müddəti yazısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Davam etmə vaxtı (saat)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Təlimatlar'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions_az',
            field=models.TextField(blank=True, null=True, verbose_name='Təlimatlar'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Təlimatlar'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Təlimatlar'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions_small',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa Təlimat yazısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions_small_az',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa Təlimat yazısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions_small_en',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa Təlimat yazısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions_small_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa Təlimat yazısı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subscription_info',
            field=models.TextField(blank=True, null=True, verbose_name='Yazılış haqqında məlumat'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subscription_info_az',
            field=models.TextField(blank=True, null=True, verbose_name='Yazılış haqqında məlumat'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subscription_info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Yazılış haqqında məlumat'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subscription_info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Yazılış haqqında məlumat'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Davam etmə vaxtı (dəqiqə)'),
        ),
    ]
