# Generated by Django 5.1.3 on 2025-11-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_exam_active_period_exam_active_period_az_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedexam',
            options={'verbose_name': 'Alınmış imtahan', 'verbose_name_plural': 'Alınmış imtahanlar'},
        ),
        migrations.AlterModelOptions(
            name='userexamsession',
            options={'verbose_name': 'İstifadəçi imtahan sessiyası', 'verbose_name_plural': 'İstifadəçi imtahan sessiyaları'},
        ),
    ]
