# Generated by Django 5.1.3 on 2025-10-10 08:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Şəkil')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Başlıq')),
                ('title_az', models.TextField(blank=True, null=True, verbose_name='Başlıq')),
                ('title_ru', models.TextField(blank=True, null=True, verbose_name='Başlıq')),
                ('title_en', models.TextField(blank=True, null=True, verbose_name='Başlıq')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Yaradılma tarixi')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Aktivdir?')),
            ],
            options={
                'verbose_name': 'Xəbərlər',
                'verbose_name_plural': 'Xəbərlər',
            },
        ),
    ]
