# Generated by Django 5.1.3 on 2025-10-10 11:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Kitab Kateqoriyası',
                'verbose_name_plural': 'Kitab Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='BookSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bookcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kitab Sub Kateqoriyası',
                'verbose_name_plural': 'Kitab Sub Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ad')),
                ('title_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ad')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ad')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ad')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Qiymət')),
                ('old_price', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Köhnə Qiymət')),
                ('ticket', models.CharField(blank=True, max_length=128, null=True, verbose_name='Etiket')),
                ('ticket_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Etiket')),
                ('ticket_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Etiket')),
                ('ticket_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Etiket')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Şəkil')),
                ('sample_pages', models.FileField(blank=True, null=True, upload_to='sample/', verbose_name='Nümunə səhifələr')),
                ('answers', models.FileField(blank=True, null=True, upload_to='image/', verbose_name='Cavablar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir?')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Baxış sayı')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bookcategory', verbose_name='Kateqoriya')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.booksubcategory', verbose_name='Sub Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kitab',
                'verbose_name_plural': 'Kitablar',
            },
        ),
    ]
