# Generated by Django 5.1.3 on 2025-10-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookcategory_booksubcategory_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Köhnə Qiymət'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Qiymət'),
        ),
    ]
