# Generated by Django 5.1.3 on 2025-10-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_old_price_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField(blank=True, null=True, verbose_name='Başlıq birinci')),
                ('title_1_az', models.TextField(blank=True, null=True, verbose_name='Başlıq birinci')),
                ('title_1_ru', models.TextField(blank=True, null=True, verbose_name='Başlıq birinci')),
                ('title_1_en', models.TextField(blank=True, null=True, verbose_name='Başlıq birinci')),
                ('title_2', models.TextField(blank=True, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_az', models.TextField(blank=True, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_ru', models.TextField(blank=True, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_en', models.TextField(blank=True, null=True, verbose_name='Başlıq ikinci')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_az', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
                ('url_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Url Başlığı')),
                ('url_title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Url Başlığı')),
                ('url_title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Url Başlığı')),
                ('url_title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Url Başlığı')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Şəkil')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Kiçik şəkil')),
                ('image_2_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil birinci yazısı')),
                ('image_2_title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil birinci yazısı')),
                ('image_2_title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil birinci yazısı')),
                ('image_2_title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil birinci yazısı')),
                ('image_2_title_2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil ikinci yazısı')),
                ('image_2_title_2_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil ikinci yazısı')),
                ('image_2_title_2_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil ikinci yazısı')),
                ('image_2_title_2_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil ikinci yazısı')),
            ],
            options={
                'verbose_name': 'Ana səhifə Slider',
                'verbose_name_plural': 'Ana səhifə Slider',
            },
        ),
        migrations.CreateModel(
            name='IndexBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1, verbose_name='Sıra')),
                ('title_1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq bikinci')),
                ('title_1_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq bikinci')),
                ('title_1_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq bikinci')),
                ('title_1_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq bikinci')),
                ('title_2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq ikinci')),
                ('books', models.ManyToManyField(blank=True, null=True, to='main.book', verbose_name='Kitablar')),
            ],
            options={
                'verbose_name': 'Ana səhifə Kitablar',
                'verbose_name_plural': 'Ana Səhifə Kitablar',
            },
        ),
    ]
