# Generated by Django 5.1.3 on 2025-10-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_indexslider_indexbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexslider',
            name='image_3_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil hərəkətli yazısı'),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='image_3_title_az',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil hərəkətli yazısı'),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='image_3_title_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil hərəkətli yazısı'),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='image_3_title_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Kiçik şəkil hərəkətli yazısı'),
        ),
    ]
