# Generated by Django 5.1.3 on 2025-10-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_indexslider_image_3_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexbooks',
            name='number',
        ),
    ]
