# Generated by Django 5.1.3 on 2025-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_pdf_title_2_pdf_title_2_az_pdf_title_2_en_and_more'),
        ('main', '0006_remove_indexbooks_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexbooks',
            options={'verbose_name': 'Ana səhifə Ödənişli Kitablar', 'verbose_name_plural': 'Ana Səhifə Ödənişli Kitablar'},
        ),
        migrations.CreateModel(
            name='IndexPDFBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq bikinci')),
                ('title_1_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq bikinci')),
                ('title_1_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq bikinci')),
                ('title_1_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq bikinci')),
                ('title_2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq ikinci')),
                ('title_2_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq ikinci')),
                ('books', models.ManyToManyField(blank=True, null=True, to='info.pdf', verbose_name='Kitablar')),
            ],
            options={
                'verbose_name': 'Ana səhifə Ödənişsiz Kitablar',
                'verbose_name_plural': 'Ana Səhifə Ödənişsiz Kitablar',
            },
        ),
    ]
