# Generated by Django 5.1.3 on 2025-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_indexbooks_options_indexpdfbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('faq', 'FAQ'), ('contact', 'Əlaqə'), ('about', 'Haqqımızda'), ('pdf', 'PDF Səhifəsi'), ('search', 'Axtarış Nəticəsi'), ('exam_list', 'İmtahan Siyahısı'), ('take_exam', 'İmtahan Hissəsi'), ('exam_finish', 'İmtahan Nəticə'), ('exam_review', 'İmtahan Rəy Yaz'), ('exam_comments', 'İmtahan Rəyləri'), ('exam_detail', 'İmtahan Məlumatı'), ('news', 'Xəbərlər'), ('news_details', 'Xəbər Detalı'), ('books', 'Kitablar'), ('book_details', 'Kitab Detalı'), ('index', 'Ana Səhifə'), ('cart', 'Səbət'), ('login', 'Daxil ol'), ('register', 'Qeydiyyatdan keç'), ('verify_email', 'Email Təsdiqi'), ('account', 'Hesabım'), ('password_reset', 'Şifrə Yenilə'), ('password_reset_verify', 'OTP Təsdiqi'), ('password_reset_confirm', 'Şifrə Yeniləmə'), ('video_list', 'Videolar'), ('video_info', 'Video Haqqında'), ('free_video', 'Pulsuz Videolar'), ('video_detail', 'Video Detalı')], max_length=50, unique=True, verbose_name='Səhifə')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Saytın Meta Başlığı',
                'verbose_name_plural': 'Saytın Meta Başlıqları',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_keywords_az',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords_az',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title'),
        ),
    ]
