# Generated by Django 5.1.3 on 2025-10-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Sıra')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Şəkil')),
                ('title_image', models.CharField(blank=True, max_length=256, null=True, verbose_name='Şəkil başlığı')),
                ('title_image_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Şəkil başlığı')),
                ('title_image_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Şəkil başlığı')),
                ('title_image_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Şəkil başlığı')),
            ],
            options={
                'verbose_name': 'Sual - Cavab',
                'verbose_name_plural': 'Sual - Cavablar',
            },
        ),
        migrations.CreateModel(
            name='QuestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Sual')),
                ('title_az', models.TextField(blank=True, null=True, verbose_name='Sual')),
                ('title_ru', models.TextField(blank=True, null=True, verbose_name='Sual')),
                ('title_en', models.TextField(blank=True, null=True, verbose_name='Sual')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Cavab')),
                ('description_az', models.TextField(blank=True, null=True, verbose_name='Cavab')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Cavab')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Cavab')),
                ('questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='info.questions', verbose_name='Sual - Cavab')),
            ],
            options={
                'verbose_name': 'Sual - Cavab',
                'verbose_name_plural': 'Sual - Cavablar',
            },
        ),
    ]
