# Generated by Django 5.1.3 on 2025-10-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
                ('location_az', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
                ('location_ru', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
                ('location_en', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
                ('location_url', models.TextField(blank=True, null=True, verbose_name='Ünvan Url Map')),
                ('phone_1', models.CharField(blank=True, max_length=18, null=True, verbose_name='Telefon nömrəsi birinci')),
                ('phone_2', models.CharField(blank=True, max_length=18, null=True, verbose_name='Telefon nömrəsi ikinci')),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email birinci')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ikinci')),
            ],
            options={
                'verbose_name': 'Əlaqə Səhifəsi',
                'verbose_name_plural': 'Əlaqə səhifəsi',
            },
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='Telefon')),
                ('messages', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
            ],
            options={
                'verbose_name': 'Əlqə Qurmaq Tələbi',
                'verbose_name_plural': 'Əlaqə Qurmaq Tələbəri',
            },
        ),
        migrations.CreateModel(
            name='SosialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='İnstagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('whatsapp', models.CharField(blank=True, max_length=128, null=True, verbose_name='Whatsapp')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='Tiktok')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
            ],
            options={
                'verbose_name': 'Sosial Akkount',
                'verbose_name_plural': 'Sosial Akkountlar',
            },
        ),
    ]
