# Generated by Django 5.1.3 on 2025-10-10 06:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_contact_contactuser_sosialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Əsas şəkil')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Əsas hərəkətli icon')),
                ('image_2_title_1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Əsas hərəkətli icon yazısı birinci')),
                ('image_2_title_2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Əsas hərəkətli icon yazısı ikinci')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Əsas icon 2')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Əsas icon 3')),
                ('statistic_1_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Birinci statistika başlıq')),
                ('statistic_1_title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Birinci statistika başlıq')),
                ('statistic_1_title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Birinci statistika başlıq')),
                ('statistic_1_title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Birinci statistika başlıq')),
                ('statistic_1_description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Birinci statistika məzmun')),
                ('statistic_1_description_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Birinci statistika məzmun')),
                ('statistic_1_description_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Birinci statistika məzmun')),
                ('statistic_1_description_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Birinci statistika məzmun')),
                ('statistic_1_icon', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Birinci statistika Şəkli')),
                ('statistic_2_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='İkinci statistika başlıq')),
                ('statistic_2_title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='İkinci statistika başlıq')),
                ('statistic_2_title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='İkinci statistika başlıq')),
                ('statistic_2_title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='İkinci statistika başlıq')),
                ('statistic_2_description', models.CharField(blank=True, max_length=128, null=True, verbose_name='İkinci statistika məzmun')),
                ('statistic_2_description_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='İkinci statistika məzmun')),
                ('statistic_2_description_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='İkinci statistika məzmun')),
                ('statistic_2_description_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='İkinci statistika məzmun')),
                ('statistic_2_icon', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='İkinci statistika Şəkli')),
            ],
            options={
                'verbose_name': 'Haqqımızda birinci hissə',
                'verbose_name_plural': 'Haqqımızda birinci hissə',
            },
        ),
        migrations.CreateModel(
            name='AboutTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Haqqımızda ikinci hissə',
                'verbose_name_plural': 'Haqqımızda ikinci hissə',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.CharField(blank=True, max_length=256, null=True, verbose_name='Rəqəm')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.CreateModel(
            name='AboutTwoStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_az', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='İcon')),
                ('about_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='info.abouttwo', verbose_name='Haqqımızda')),
            ],
            options={
                'verbose_name': 'Haqqımızda ikinci hissə statistika',
                'verbose_name_plural': 'Haqqımızda ikinci hissə statistikalar',
            },
        ),
    ]
