# Generated by Django 5.1.3 on 2025-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_about_abouttwo_statistic_abouttwostatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Şəkil')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='PDF')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdirmi?')),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDF-lər',
            },
        ),
    ]
