# Generated by Django 5.1.3 on 2025-10-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='title_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq 2'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='title_2_az',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq 2'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='title_2_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq 2'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='title_2_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq 2'),
        ),
    ]
