# Generated by Django 5.1.3 on 2025-10-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_pdf_title_2_pdf_title_2_az_pdf_title_2_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoFavicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_Logo', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Header Logo')),
                ('footer_Logo', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Footer Logo')),
                ('footer_description', models.TextField(blank=True, null=True, verbose_name='Footer loqo altı Məzmun')),
                ('footer_description_az', models.TextField(blank=True, null=True, verbose_name='Footer loqo altı Məzmun')),
                ('footer_description_ru', models.TextField(blank=True, null=True, verbose_name='Footer loqo altı Məzmun')),
                ('footer_description_en', models.TextField(blank=True, null=True, verbose_name='Footer loqo altı Məzmun')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Loqo və Favicon',
                'verbose_name_plural': 'Loqo və Favicon',
            },
        ),
    ]
