# Generated by Django 5.1.3 on 2025-10-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_logofavicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logofavicon',
            old_name='footer_Logo',
            new_name='footer_logo',
        ),
        migrations.RenameField(
            model_name='logofavicon',
            old_name='header_Logo',
            new_name='header_logo',
        ),
    ]
