# Generated by Django 5.1.3 on 2025-10-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_rename_footer_logo_logofavicon_footer_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Abonə olma tarixi')),
            ],
            options={
                'verbose_name': 'Abonə Olanlar',
                'verbose_name_plural': 'Abonə Olanlar',
            },
        ),
    ]
