# Generated by Django 5.1.3 on 2025-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Password Reset')], default='register', max_length=20),
        ),
    ]
