# Generated by Django 5.1.3 on 2025-10-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
            ],
            options={
                'verbose_name': 'Video Kateqoriyası',
                'verbose_name_plural': 'Video Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='VideoSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videocategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Video Sub Kateqoriyası',
                'verbose_name_plural': 'Video Sub Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Video Şəkli')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Video')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Başlıq')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Qiymət')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Köhnə qiymət')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videocategory', verbose_name='Kateqoriya')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videosubcategory', verbose_name='Sub kateqoriya')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
