# Generated by Django 5.1.3 on 2025-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Köhnə qiymət'),
        ),
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Qiymət'),
        ),
    ]
