# Generated by Django 5.1.3 on 2025-10-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_old_price_alter_video_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Köhnə qiymət'),
        ),
        migrations.AlterField(
            model_name='video',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Qiymət'),
        ),
    ]
