# Generated by Django 5.1.3 on 2025-10-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_old_price_alter_video_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='active_period_days',
            field=models.TextField(blank=True, null=True, verbose_name='Aktiv olma müddəti'),
        ),
        migrations.AddField(
            model_name='video',
            name='active_period_days_az',
            field=models.TextField(blank=True, null=True, verbose_name='Aktiv olma müddəti'),
        ),
        migrations.AddField(
            model_name='video',
            name='active_period_days_en',
            field=models.TextField(blank=True, null=True, verbose_name='Aktiv olma müddəti'),
        ),
        migrations.AddField(
            model_name='video',
            name='active_period_days_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Aktiv olma müddəti'),
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_hours',
            field=models.PositiveIntegerField(default=2, verbose_name='Davam etmə vaxtı (saat)'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Davam etmə vaxtı (dəqiqə)'),
        ),
        migrations.AddField(
            model_name='video',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Təlimatlar'),
        ),
        migrations.AddField(
            model_name='video',
            name='instructions_az',
            field=models.TextField(blank=True, null=True, verbose_name='Təlimatlar'),
        ),
        migrations.AddField(
            model_name='video',
            name='instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Təlimatlar'),
        ),
        migrations.AddField(
            model_name='video',
            name='instructions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Təlimatlar'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi?'),
        ),
        migrations.AddField(
            model_name='video',
            name='subscription_info',
            field=models.TextField(blank=True, null=True, verbose_name='Yazılış haqqında məlumat'),
        ),
        migrations.AddField(
            model_name='video',
            name='subscription_info_az',
            field=models.TextField(blank=True, null=True, verbose_name='Yazılış haqqında məlumat'),
        ),
        migrations.AddField(
            model_name='video',
            name='subscription_info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Yazılış haqqında məlumat'),
        ),
        migrations.AddField(
            model_name='video',
            name='subscription_info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Yazılış haqqında məlumat'),
        ),
    ]
