# Generated by Django 5.1.3 on 2025-10-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_active_period_days_video_active_period_days_az_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='active_period_days_az',
            new_name='active_period',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='active_period_days_en',
            new_name='active_period_az',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='active_period_days_ru',
            new_name='active_period_en',
        ),
        migrations.AddField(
            model_name='video',
            name='active_period_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Aktiv olma müddəti'),
        ),
        migrations.AlterField(
            model_name='video',
            name='active_period_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Aktiv olma müddəti (günlərlə)'),
        ),
    ]
