# Generated by Django 5.1.3 on 2025-10-13 13:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_rename_active_period_days_az_video_active_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='instructions_small',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa Təlimat yazısı'),
        ),
        migrations.AddField(
            model_name='video',
            name='instructions_small_az',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa Təlimat yazısı'),
        ),
        migrations.AddField(
            model_name='video',
            name='instructions_small_en',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa Təlimat yazısı'),
        ),
        migrations.AddField(
            model_name='video',
            name='instructions_small_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Qısa Təlimat yazısı'),
        ),
        migrations.AlterField(
            model_name='video',
            name='active_period',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aktiv olma müddəti yazısı'),
        ),
        migrations.AlterField(
            model_name='video',
            name='active_period_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aktiv olma müddəti yazısı'),
        ),
        migrations.AlterField(
            model_name='video',
            name='active_period_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aktiv olma müddəti yazısı'),
        ),
        migrations.AlterField(
            model_name='video',
            name='active_period_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Aktiv olma müddəti yazısı'),
        ),
    ]
