# Generated by Django 5.1.3 on 2025-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_instructions_small_video_instructions_small_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Davam etmə vaxtı (saat)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Davam etmə vaxtı (dəqiqə)'),
        ),
    ]
