# Generated by Django 5.1.3 on 2025-10-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_video_duration_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Başlıq')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Şəkil')),
                ('video', models.FileField(blank=True, null=True, upload_to='free_video/', verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir?')),
            ],
            options={
                'verbose_name': 'Ödənişsiz videolar',
                'verbose_name_plural': 'Ödənişsiz videolar',
            },
        ),
    ]
