# Generated by Django 5.1.3 on 2025-10-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_freevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freevideo',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
