# Generated by Django 5.1.3 on 2025-11-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_purchasedvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedvideo',
            options={'verbose_name': 'Alınmış video', 'verbose_name_plural': 'Alınmış videolar'},
        ),
    ]
